### ISSUE TITLE
Error when using a flow-action-card

### ISSUE THREAD

**Issue by mjvdboon** [aartse/athom.duco#1]
Goodmorning,

When I change the ventilation-state through the app (the Duco-device), the state is changed. When I want to do the same action only initiated through a flow, I receive a 400-error code (see picture). 

<img width="261" alt="Error-Code ActionCard" src="https://github.com/user-attachments/assets/9d3a5de1-bb96-4066-a6f7-5e04b6e90647">

**Comment by aartse** [comment]
> Goodmorning,
> 
> When I change the ventilation-state through the app (the Duco-device), the state is changed. When I want to do the same action only initiated through a flow, I receive a 400-error code (see picture).
> 
> <img alt="Error-Code ActionCard" width="261" src="https://private-user-images.githubusercontent.com/186277971/380099036-9d3a5de1-bb96-4066-a6f7-5e04b6e90647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTI2MDIsIm5iZiI6MTcyOTg1MjMwMiwicGF0aCI6Ii8xODYyNzc5NzEvMzgwMDk5MDM2LTlkM2E1ZGUxLWJiOTYtNDA2Ni1hNmY3LTVlMDRiNmU5MDY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMDMxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjg1MzQ4NmYyZGZjY2ZmYmE1OTRhMTM2MDFkOTEzNzczNzViNGI2MTI2YTcwNTdjNjcwYThkMGZjOTFiNjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZI9IEOKYqb4mjDuGAhgd09bmnzNCT5OOu-slGNMabog">

Thank you for reporting this issue. I also recieved a trace report via homey with te same error. I’ll look into it.

what kind of Duco-box do you have?

**Comment by mjvdboon** [comment]
Hi,

Thank you for your quick response. And of course, thank you for making this app. 

I have a Duco Silent Connect Box together with a communication board.

**Comment by mjvdboon** [comment]
Great! Many thanks!

**Comment by aartse** [comment]
version 1.2.1 is released, closing this issue.
